#[colors]
#text = "#282a36"

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#232839"
bright_foreground = "#ffffff"
foreground = "#F8F8F2"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[cursor.style]
blinking = "On"
shape = "Beam"

[font.bold]
family = "Caskaydia Cove NerdFont"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove NerdFont"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove NerdFont"
style = "Italic"

[font.normal]
family = "Caskaydia Cove NerdFont"
style = "Regular"

[window]
dynamic_title = false
startup_mode = "Windowed"
title = "Terminal"


